module Config
    APPLNAME = "openrtm_consoleout"
    TARGET = "zybo_z7_gcc"
    TEMPMAKEFILE ="../appli/Makefile"
    LIBS     = <<LIBS_END
        ../../OpenRTM-aist/build_arm/src/lib/rtm/libRTC2-static.a
        ../../OpenRTM-aist/build_arm/utils/openrtmNames/libOpenrtmNamesPlugin-static.a
        ../../RtORB/lib/CXX/libRtORB_cpp.a
        ../../RtORB/lib/libRtORB.a
        -lstdc++
        -lm
LIBS_END
    LDFLAGS =<<LDFLAGS_END
        -Wl,--allow-multiple-definition
        -Wl,-Map=asp_openrtm.map
LDFLAGS_END
    SRC_FILES = <<SRC_FILES
    #APPL
        ../appli/ftl_gettimeofday.c
        ../appli/ftl_string.c
        ../appli/ftl_getopt.c
        ../appli/ftl_malloc.c
        ../appli/echo.c
        ../appli/tlsf.c
        ../appli/ConsoleOut.cpp
        ../appli/ConsoleOutComp.cpp
    #BSP
        ../bsp/standalone/src/arm/cortexa9/xtime_l.c
        ../bsp/standalone/src/arm/cortexa9/xl2cc_counter.c
        ../bsp/standalone/src/arm/cortexa9/sleep.c
        ../bsp/standalone/src/arm/cortexa9/xil_cache.c
        ../bsp/standalone/src/arm/cortexa9/xil_mmu.c
        ../bsp/standalone/src/arm/cortexa9/xil_misc_psreset_api.c
        ../bsp/standalone/src/arm/cortexa9/usleep.c
        ../bsp/standalone/src/arm/common/vectors.c
        ../bsp/standalone/src/arm/common/xil_exception.c
        ../bsp/standalone/src/arm/common/xil_spinlock.c
        ../bsp/standalone/src/arm/common/gcc/time.c
        ../bsp/standalone/src/arm/common/gcc/sbrk.c
        ../bsp/standalone/src/arm/common/gcc/cpputest_time.c
        ../bsp/standalone/src/arm/common/gcc/abort.c
        ../bsp/standalone/src/arm/common/gcc/gettimeofday.c
        ../bsp/standalone/src/arm/common/gcc/getpid.c
        ../bsp/standalone/src/arm/common/gcc/write.c
        ../bsp/standalone/src/arm/common/gcc/close.c
        ../bsp/standalone/src/arm/common/gcc/_sbrk.c
        ../bsp/standalone/src/arm/common/gcc/isatty.c
        ../bsp/standalone/src/arm/common/gcc/open.c
        ../bsp/standalone/src/arm/common/gcc/lseek.c
        ../bsp/standalone/src/arm/common/gcc/kill.c
        ../bsp/standalone/src/arm/common/gcc/read.c
        ../bsp/standalone/src/arm/common/gcc/errno.c
        ../bsp/standalone/src/arm/common/gcc/unlink.c
        ../bsp/standalone/src/arm/common/gcc/getentropy.c
        ../bsp/standalone/src/arm/common/gcc/_open.c
        ../bsp/standalone/src/arm/common/gcc/fstat.c
        ../bsp/standalone/src/arm/common/gcc/fcntl.c
        ../bsp/standalone/src/arm/common/xpm_counter.c
        ../bsp/standalone/src/arm/common/putnum.c
        ../bsp/standalone/src/arm/common/xil_sleeptimer.c
        ../bsp/standalone/src/common/xil_printf.c
        ../bsp/standalone/src/common/xil_testcache.c
        ../bsp/standalone/src/common/inbyte.c
        ../bsp/standalone/src/common/outbyte.c
        ../bsp/standalone/src/common/xil_util.c
        ../bsp/standalone/src/common/xil_sleepcommon.c
        ../bsp/standalone/src/common/intr/xinterrupt_wrap.c
        ../bsp/standalone/src/common/xil_testmem.c
        ../bsp/standalone/src/common/xil_mem.c
        ../bsp/standalone/src/common/xplatform_info.c
        ../bsp/standalone/src/common/xil_assert.c
        ../bsp/standalone/src/common/xil_sutil.c
        ../bsp/standalone/src/common/clocking/xil_clocking.c
        ../bsp/standalone/src/common/xil_testio.c
        ../bsp/standalone/src/common/print.c
        ../bsp/standalone/src/common/xpm_init.c
        ../bsp/standalone/src/xcortexa9_g.c
        ../bsp/libsrc/emacps/src/xemacps_intr.c
        ../bsp/libsrc/emacps/src/xemacps_g.c
        ../bsp/libsrc/emacps/src/xemacps_hw.c
        ../bsp/libsrc/emacps/src/xemacps_control.c
        ../bsp/libsrc/emacps/src/xemacps_bdring.c
        ../bsp/libsrc/emacps/src/xemacps.c
        ../bsp/libsrc/lwip/src/xtopology_g.c
        ../bsp/libsrc/fsbl/scugic/src/xscugic_g.c
        ../bsp/libsrc/fsbl/scugic/src/xscugic_hw.c
        ../bsp/libsrc/fsbl/scugic/src/xscugic_intr.c
        ../bsp/libsrc/fsbl/scugic/src/xscugic_sinit.c
        ../bsp/libsrc/fsbl/scugic/src/xscugic.c
        ../bsp/standalone/src/arm/cortexa9/gcc/translation_table.S
    #LWIP
        ../../lwip/contrib/ports/toppers/sys_arch.c
        ../../lwip/contrib/ports/xilinx/netif/xadapter.c
        ../../lwip/contrib/ports/xilinx/netif/xemacpsif_hw.c
        ../../lwip/contrib/ports/xilinx/netif/xemacpsif_dma.c
        ../../lwip/contrib/ports/xilinx/netif/xemacpsif.c
        ../../lwip/contrib/ports/xilinx/netif/xpqueue.c
        ../../lwip/contrib/ports/xilinx/netif/xemacpsif_physpeed.c
        ../../lwip/src/netif/lowpan6_common.c
        ../../lwip/src/netif/bridgeif_fdb.c
        ../../lwip/src/netif/bridgeif.c
        ../../lwip/src/netif/zepif.c
        ../../lwip/src/netif/ppp/auth.c
        ../../lwip/src/netif/ppp/pppoe.c
        ../../lwip/src/netif/ppp/ipcp.c
        ../../lwip/src/netif/ppp/mppe.c
        ../../lwip/src/netif/ppp/ppp.c
        ../../lwip/src/netif/ppp/chap-md5.c
        ../../lwip/src/netif/ppp/vj.c
        ../../lwip/src/netif/ppp/ccp.c
        ../../lwip/src/netif/ppp/upap.c
        ../../lwip/src/netif/ppp/chap-new.c
        ../../lwip/src/netif/ppp/eui64.c
        ../../lwip/src/netif/ppp/ipv6cp.c
        ../../lwip/src/netif/ppp/pppapi.c
        ../../lwip/src/netif/ppp/ecp.c
        ../../lwip/src/netif/ppp/pppcrypt.c
        ../../lwip/src/netif/ppp/eap.c
        ../../lwip/src/netif/ppp/multilink.c
        ../../lwip/src/netif/ppp/magic.c
        ../../lwip/src/netif/ppp/chap_ms.c
        ../../lwip/src/netif/ppp/polarssl/arc4.c
        ../../lwip/src/netif/ppp/polarssl/des.c
        ../../lwip/src/netif/ppp/polarssl/sha1.c
        ../../lwip/src/netif/ppp/polarssl/md4.c
        ../../lwip/src/netif/ppp/polarssl/md5.c
        ../../lwip/src/netif/ppp/demand.c
        ../../lwip/src/netif/ppp/utils.c
        ../../lwip/src/netif/ppp/lcp.c
        ../../lwip/src/netif/ppp/pppos.c
        ../../lwip/src/netif/ppp/fsm.c
        ../../lwip/src/netif/ppp/pppol2tp.c
        ../../lwip/src/netif/lowpan6.c
        ../../lwip/src/netif/lowpan6_ble.c
        ../../lwip/src/netif/ethernet.c
        ../../lwip/src/api/if_api.c
        ../../lwip/src/api/api_lib.c
        ../../lwip/src/api/netbuf.c
        ../../lwip/src/api/sockets.c
        ../../lwip/src/api/tcpip.c
        ../../lwip/src/api/netdb.c
        ../../lwip/src/api/api_msg.c
        ../../lwip/src/api/netifapi.c
        ../../lwip/src/api/err.c
        ../../lwip/src/core/mem.c
        ../../lwip/src/core/altcp.c
        ../../lwip/src/core/stats.c
        ../../lwip/src/core/ipv4/dhcp.c
        ../../lwip/src/core/ipv4/ip4.c
        ../../lwip/src/core/ipv4/ip4_addr.c
        ../../lwip/src/core/ipv4/ip4_frag.c
        ../../lwip/src/core/ipv4/igmp.c
        ../../lwip/src/core/ipv4/acd.c
        ../../lwip/src/core/ipv4/etharp.c
        ../../lwip/src/core/ipv4/icmp.c
        ../../lwip/src/core/ipv4/autoip.c
        ../../lwip/src/core/raw.c
        ../../lwip/src/core/tcp_out.c
        ../../lwip/src/core/tcp_in.c
        ../../lwip/src/core/udp.c
        ../../lwip/src/core/def.c
        ../../lwip/src/core/pbuf.c
        ../../lwip/src/core/ipv6/inet6.c
        ../../lwip/src/core/ipv6/ip6_frag.c
        ../../lwip/src/core/ipv6/ip6.c
        ../../lwip/src/core/ipv6/mld6.c
        ../../lwip/src/core/ipv6/icmp6.c
        ../../lwip/src/core/ipv6/ethip6.c
        ../../lwip/src/core/ipv6/nd6.c
        ../../lwip/src/core/ipv6/dhcp6.c
        ../../lwip/src/core/ipv6/ip6_addr.c
        ../../lwip/src/core/init.c
        ../../lwip/src/core/timeouts.c
        ../../lwip/src/core/memp.c
        ../../lwip/src/core/altcp_alloc.c
        ../../lwip/src/core/netif.c
        ../../lwip/src/core/sys.c
        ../../lwip/src/core/dns.c
        ../../lwip/src/core/tcp.c
        ../../lwip/src/core/ip.c
        ../../lwip/src/core/inet_chksum.c
        ../../lwip/src/core/altcp_tcp.c
SRC_FILES
    APPL_DIRS = <<APPL_DIRS_END
        ../appli/
        ../../lwip/contrib/ports/toppers/include/
        ../../lwip/src/include/
        ../bsp/standalone/src/arm/common/
        ../bsp/include/
        ../../lwip/src/include/
        ../../lwip/contrib/ports/xilinx/include/
        ../../RtORB/include/
        ../../RtORB/include/RtORB/functions/
        ../../lwip/src/include/lwip/
        ../../OpenRTM-aist/src/lib/
        ../../OpenRTM-aist/build_arm/src/lib/
        ../../OpenRTM-aist/build_arm/src/lib/rtm/idl/
        ../../OpenRTM-aist/src/lib/coil/lwip/
        ../../OpenRTM-aist/src/lib/coil/lwip/coil/std_include/
        ../../OpenRTM-aist/src/lib/coil/common/
        ../../OpenRTM-aist/utils/
APPL_DIRS_END
    CDEFS =<<CDEFS_END
        -DDLL_PLUGIN=
        -DEXTERN=extern
        -DLWIP
        -D_SYS_SELECT_H
        -DTLSF_USE_LOCKS
        -DUSE_MMAP=0
        -DCONFIG_LINKSPEED_AUTODETECT
        -DSDT
        -DXPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ=666666687
        -D__FILENAME__=__FILE__ -DconfigASSERT=
CDEFS_END
end
